package detect

import (
	"path/filepath"
	"regexp"
	"strings"
)

// sensitivePatterns matches paths that likely contain secrets or
// credentials. Files matching any of these are dropped from the corpus
// silently — graphify's policy is that surfacing the existence of a
// `.env.production` file in a report is itself a leak.
//
// The set tracks graphify upstream verbatim so cross-tool consumers
// agree on what's skipped.
var sensitivePatterns = []*regexp.Regexp{
	// dotenv: .env, .envrc, .env.production, etc.
	regexp.MustCompile(`(^|[\\/])\.(env|envrc)(\..*)?$`),
	// keys & certs
	regexp.MustCompile(`(?i)\.(pem|key|p12|pfx|cert|crt|der|p8)$`),
	// credentials / secrets / tokens. graphify-parity. Go regexp \b
	// treats underscore as a word char, so underscore-separated
	// filenames (token_handler.go, password_test.go) DON'T match and
	// stay in the corpus. Hyphen and dot ARE boundaries, so
	// "token-handler.json" or "tokens.yaml" do match — accepted as a
	// reasonable trade-off since hyphenated credential-bearing
	// filenames are rare in source trees.
	regexp.MustCompile(`(?i)\b(credential|secret|passwd|password|token|private_key)s?\b`),
	// SSH keypairs
	regexp.MustCompile(`(id_rsa|id_dsa|id_ecdsa|id_ed25519)(\.pub)?$`),
	// dotfiles that store auth
	regexp.MustCompile(`(?i)(\.netrc|\.pgpass|\.htpasswd)$`),
	// cloud creds
	regexp.MustCompile(`(?i)(aws_credentials|gcloud_credentials|service.account)`),
	// Path-anchored cloud / infra creds. These have generic basenames
	// (`credentials`, `config`) so they're matched by parent-directory
	// rather than basename — that's why IsSensitive feeds both the full
	// path and the basename through every pattern.
	regexp.MustCompile(`(?i)(^|/)\.aws/(credentials|config)$`),
	regexp.MustCompile(`(?i)(^|/)\.kube/config$`),
	regexp.MustCompile(`(?i)(^|/)\.docker/config\.json$`),
	regexp.MustCompile(`(?i)(^|/)\.gnupg/`),
	// Package-manager auth files. .npmrc/.pypirc/.netrc-style stores
	// regularly carry private-registry tokens — common enough that
	// committing them is a top-10 leak in public repos.
	regexp.MustCompile(`(?i)(^|/)\.(npmrc|pypirc|gem/credentials|cargo/credentials(\.toml)?)$`),
	// Terraform state files leak both backend creds and resource
	// secrets in plaintext — high-impact leak class. Backup suffix is
	// auto-generated by `terraform apply` so it gets the same
	// treatment.
	regexp.MustCompile(`(?i)\.tfstate(\.backup)?$`),
	regexp.MustCompile(`(?i)\.tfvars(\.json)?$`),
	// Firebase admin SDK JSON keys land with a recognizable suffix.
	regexp.MustCompile(`(?i)firebase-adminsdk[^/]*\.json$`),
	// Generic API-key-ish basenames not caught by the `token|secret|
	// credential` pattern above because they're separated by hyphen
	// or underscore boundaries the \b form already covered, but
	// "apikey" as one word slips through.
	regexp.MustCompile(`(?i)\b(api[-_]?key|access[-_]?token|client[-_]?secret)s?\b`),
}

// IsSensitive reports whether path looks like a credential / secret store
// that should be skipped without surfacing its existence. Matching is
// case-insensitive on the basename for most patterns.
func IsSensitive(path string) bool {
	// Normalize to forward slashes so the regex patterns work on Windows
	// paths without per-platform branching.
	candidate := filepath.ToSlash(path)
	// Some patterns (dotenv) look at the slash-prefixed form; the rest
	// only need the basename. Cheapest to pass both shapes.
	base := candidate
	if i := strings.LastIndex(candidate, "/"); i >= 0 {
		base = candidate[i+1:]
	}
	for _, re := range sensitivePatterns {
		if re.MatchString(candidate) || re.MatchString(base) {
			return true
		}
	}
	return false
}
