// Package wiki turns a clustered+analyzed graph into a Wikipedia-style
// markdown directory: index.md catalogs everything, one article per
// community surfaces its key concepts and cross-community connections,
// one article per god node surfaces its neighbors grouped by relation.
//
// The wiki is meant for AI assistants to crawl instead of grepping raw
// source files. The agent skill prompts in safishamsi/graphify v7 tell
// the agent to navigate `graphify-out/wiki/index.md` first when present,
// then drill into community articles for context before reading source.
//
// graphify's analogous module is graphify/wiki.py (255 lines); shapes
// and headings are kept compatible so cross-tool consumers don't need
// two parsers.
package wiki

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/julianshen/gogfy/internal/fsutil"
	"github.com/julianshen/gogfy/internal/schema"
)

// Options tunes article generation. Zero-value is graphify-parity.
type Options struct {
	// CommunityLabels overrides the default "Community <N>" name per
	// community ID. graphify uses LLM-generated labels; gogfy has no
	// LLM step today, but the hook is here for future use.
	CommunityLabels map[string]string
	// GodNodes lists nodes to emit dedicated articles for. The wiki
	// will produce one article per entry; nodes not in the graph are
	// silently skipped (consistent with graphify's behavior).
	GodNodes []schema.Node
}

// Generate writes the wiki to outDir. Existing .md files in outDir are
// removed first — community labels can change between runs and orphan
// articles would otherwise accumulate. Returns the number of articles
// written (excluding index.md).
//
// Error contract:
//   - returns an error if outDir can't be created or written
//   - returns an error if there are no communities (refuses to clear an
//     existing wiki directory based on empty input — matches graphify)
func Generate(nodes []schema.Node, edges []schema.Edge, outDir string, opts Options) (int, error) {
	communities := groupByCommunity(nodes)
	if len(communities) == 0 {
		return 0, fmt.Errorf("wiki: no communities in graph — run cluster first")
	}

	if err := os.MkdirAll(outDir, 0755); err != nil {
		return 0, fmt.Errorf("wiki: create %s: %w", outDir, err)
	}
	if err := clearStaleArticles(outDir); err != nil {
		return 0, err
	}

	labels := opts.CommunityLabels
	if labels == nil {
		labels = map[string]string{}
	}
	for cid := range communities {
		if _, ok := labels[cid]; !ok {
			labels[cid] = "Community " + cid
		}
	}

	nodeMap := indexNodes(nodes)
	adj := buildAdjacency(nodes, edges)
	degree := buildDegree(edges)
	auditByCommunity := buildCommunityAudit(edges, nodeMap)

	count := 0
	used := map[string]bool{}
	// Assign slugs FIRST (community + god-node) so cross-document links
	// can resolve to actual filenames rather than human labels. Label
	// collisions (two communities both called "Examples", or a god node
	// sharing a community's label) would otherwise produce ambiguous
	// `[[Label]]` wiki links — pinned by Markdown's stricter
	// `[Label](file.md)` form.
	communitySlugs := map[string]string{}
	for _, cid := range sortedKeys(communities) {
		communitySlugs[cid] = uniqueSlug(used, safeFilename(labels[cid]))
	}
	godSlugs := map[string]string{}
	emittedGods := make([]schema.Node, 0, len(opts.GodNodes))
	for _, g := range opts.GodNodes {
		if _, ok := nodeMap[g.ID]; !ok {
			continue
		}
		godSlugs[g.ID] = uniqueSlug(used, safeFilename(g.Label))
		emittedGods = append(emittedGods, g)
	}

	// Community articles, sorted by community ID for determinism.
	for _, cid := range sortedKeys(communities) {
		article := communityArticle(cid, communities[cid], labels, nodeMap, adj, degree, auditByCommunity[cid], communitySlugs)
		if err := writeArticle(filepath.Join(outDir, communitySlugs[cid]+".md"), article); err != nil {
			return count, err
		}
		count++
	}

	// God node articles. Skipping any god nodes not present in the graph
	// was already done above by emittedGods — we walk that list here so
	// the article-emission loop matches what the index references.
	for _, g := range emittedGods {
		article := godNodeArticle(g, nodeMap, adj, labels, degree, communitySlugs)
		if err := writeArticle(filepath.Join(outDir, godSlugs[g.ID]+".md"), article); err != nil {
			return count, err
		}
		count++
	}

	idx := indexArticle(communities, labels, emittedGods, communitySlugs, godSlugs, len(nodes), len(edges))
	if err := writeArticle(filepath.Join(outDir, "index.md"), idx); err != nil {
		return count, err
	}
	// Mark the dir as gogfy-owned so subsequent runs can safely
	// clearStaleArticles. Content is informational; the existence of
	// the file is what matters.
	if err := fsutil.WriteFileAtomic(filepath.Join(outDir, wikiMarkerFile),
		[]byte("# generated by gogfy wiki — safe to delete with the rest of this directory\n"),
		0644); err != nil {
		return count, err
	}
	return count, nil
}

// groupByCommunity buckets nodes by their Community field. Nodes whose
// Community is empty are skipped — they predate clustering or were
// excluded; either way they have nothing meaningful to summarize.
func groupByCommunity(nodes []schema.Node) map[string][]schema.Node {
	out := map[string][]schema.Node{}
	for _, n := range nodes {
		if n.Community == "" {
			continue
		}
		out[n.Community] = append(out[n.Community], n)
	}
	return out
}

func indexNodes(nodes []schema.Node) map[string]schema.Node {
	out := make(map[string]schema.Node, len(nodes))
	for _, n := range nodes {
		out[n.ID] = n
	}
	return out
}

// buildAdjacency yields undirected neighbor lists keyed by node ID.
// Treats edges as undirected (mirrors graphify's nx.Graph), since the
// graph queries the wiki supports — "what's related to X" — don't care
// about direction.
func buildAdjacency(nodes []schema.Node, edges []schema.Edge) map[string][]string {
	adj := make(map[string][]string, len(nodes))
	for _, e := range edges {
		adj[e.Source] = append(adj[e.Source], e.Target)
		adj[e.Target] = append(adj[e.Target], e.Source)
	}
	return adj
}

func buildDegree(edges []schema.Edge) map[string]int {
	d := map[string]int{}
	for _, e := range edges {
		d[e.Source]++
		d[e.Target]++
	}
	return d
}

// communityAudit tracks the per-confidence edge count + total for one
// community's audit-trail section.
type communityAudit struct {
	counts map[schema.Confidence]int
	total  int
}

// buildCommunityAudit walks edges ONCE producing per-community confidence
// counts. Without this, communityArticle's audit section would re-walk
// every edge for every community — O(C × E) where the precomputed form
// is O(E). For a graph with 50 communities and 10k edges, this is the
// difference between 500k and 10k iterations on the wiki cold path.
func buildCommunityAudit(edges []schema.Edge, nodeMap map[string]schema.Node) map[string]communityAudit {
	out := map[string]communityAudit{}
	bump := func(cid string, c schema.Confidence) {
		entry, ok := out[cid]
		if !ok {
			entry = communityAudit{counts: map[schema.Confidence]int{}}
		}
		entry.counts[c]++
		entry.total++
		out[cid] = entry
	}
	for _, e := range edges {
		srcC := nodeMap[e.Source].Community
		dstC := nodeMap[e.Target].Community
		// An edge touches a community if either endpoint is a member.
		// When both endpoints are in the same community, count it once
		// for that community; when they're in different communities,
		// count it for both (it's a cross-community edge that shows up
		// in both audit trails).
		if srcC != "" {
			bump(srcC, e.Confidence)
		}
		if dstC != "" && dstC != srcC {
			bump(dstC, e.Confidence)
		}
	}
	return out
}

// communityArticle renders the per-community article: key concepts (top
// 25 by degree), cross-community relationships, source files, and an
// audit-trail breakdown by edge confidence.
func communityArticle(cid string, members []schema.Node, labels map[string]string, nodeMap map[string]schema.Node, adj map[string][]string, degree map[string]int, audit communityAudit, communitySlugs map[string]string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", labels[cid])
	fmt.Fprintf(&b, "> %d nodes\n\n", len(members))

	renderKeyConcepts(&b, members, degree)
	renderRelationships(&b, cid, members, adj, nodeMap, labels, communitySlugs)
	renderSourceFiles(&b, members)
	renderAuditTrail(&b, audit)

	b.WriteString("---\n\n*Part of the gogfy knowledge wiki. See [index](index.md) to navigate.*\n")
	return b.String()
}

func renderKeyConcepts(b *strings.Builder, members []schema.Node, degree map[string]int) {
	sort.Slice(members, func(i, j int) bool {
		return degree[members[i].ID] > degree[members[j].ID]
	})
	topN := min(25, len(members))
	b.WriteString("## Key Concepts\n\n")
	for _, n := range members[:topN] {
		src := ""
		if n.SourceFile != "" {
			src = fmt.Sprintf(" — `%s`", n.SourceFile)
		}
		fmt.Fprintf(b, "- **%s** (%d connections)%s\n", n.Label, degree[n.ID], src)
	}
	if remaining := len(members) - topN; remaining > 0 {
		fmt.Fprintf(b, "- *... and %d more nodes in this community*\n", remaining)
	}
	b.WriteString("\n")
}

func renderRelationships(b *strings.Builder, cid string, members []schema.Node, adj map[string][]string, nodeMap map[string]schema.Node, labels map[string]string, communitySlugs map[string]string) {
	// Cross-community counts keyed by OTHER community's cid (not label),
	// since labels can collide but cid is stable. We render with the
	// (label, slug) pair for that cid.
	crossCounts := map[string]int{}
	for _, m := range members {
		for _, neighborID := range adj[m.ID] {
			n, ok := nodeMap[neighborID]
			if !ok {
				continue
			}
			if n.Community != "" && n.Community != cid {
				crossCounts[n.Community]++
			}
		}
	}
	type crossEntry struct {
		cid   string
		label string
		count int
	}
	crosses := make([]crossEntry, 0, len(crossCounts))
	for othCid, v := range crossCounts {
		crosses = append(crosses, crossEntry{othCid, labels[othCid], v})
	}
	sort.Slice(crosses, func(i, j int) bool {
		if crosses[i].count != crosses[j].count {
			return crosses[i].count > crosses[j].count
		}
		return crosses[i].label < crosses[j].label
	})

	b.WriteString("## Relationships\n\n")
	if len(crosses) == 0 {
		b.WriteString("- No strong cross-community connections detected\n\n")
		return
	}
	for _, c := range crosses[:min(12, len(crosses))] {
		slug, ok := communitySlugs[c.cid]
		if !ok {
			// Community had no slug emitted (defensive — shouldn't
			// happen given Generate's order, but a missing slug means
			// we'd write a dead link). Render label-only.
			fmt.Fprintf(b, "- %s (%d shared connections)\n", c.label, c.count)
			continue
		}
		fmt.Fprintf(b, "- [%s](%s.md) (%d shared connections)\n", c.label, slug, c.count)
	}
	b.WriteString("\n")
}

func renderSourceFiles(b *strings.Builder, members []schema.Node) {
	srcSet := map[string]bool{}
	for _, m := range members {
		if m.SourceFile != "" {
			srcSet[m.SourceFile] = true
		}
	}
	if len(srcSet) == 0 {
		return
	}
	sources := make([]string, 0, len(srcSet))
	for s := range srcSet {
		sources = append(sources, s)
	}
	sort.Strings(sources)
	b.WriteString("## Source Files\n\n")
	for _, s := range sources[:min(20, len(sources))] {
		fmt.Fprintf(b, "- `%s`\n", s)
	}
	b.WriteString("\n")
}

func renderAuditTrail(b *strings.Builder, audit communityAudit) {
	b.WriteString("## Audit Trail\n\n")
	for _, c := range []schema.Confidence{schema.Extracted, schema.Inferred, schema.Ambiguous} {
		n := audit.counts[c]
		pct := 0
		if audit.total > 0 {
			pct = (n * 100) / audit.total
		}
		fmt.Fprintf(b, "- %s: %d (%d%%)\n", c.String(), n, pct)
	}
	b.WriteString("\n")
}

func godNodeArticle(g schema.Node, nodeMap map[string]schema.Node, adj map[string][]string, labels map[string]string, degree map[string]int, communitySlugs map[string]string) string {
	var b strings.Builder
	src := ""
	if g.SourceFile != "" {
		src = fmt.Sprintf(" · `%s`", g.SourceFile)
	}
	fmt.Fprintf(&b, "# %s\n\n", g.Label)
	fmt.Fprintf(&b, "> God node · %d connections%s\n\n", degree[g.ID], src)

	if g.Community != "" {
		cname := labels[g.Community]
		if cname == "" {
			cname = "Community " + g.Community
		}
		if slug, ok := communitySlugs[g.Community]; ok {
			fmt.Fprintf(&b, "**Community:** [%s](%s.md)\n\n", cname, slug)
		} else {
			fmt.Fprintf(&b, "**Community:** %s\n\n", cname)
		}
	}

	// graphify groups neighbors by edge relation (### calls / ### imports).
	// adj here is relation-less, so we list a flat degree-ordered set —
	// a follow-up using an edge-indexed walker can add the grouping.
	neighbors := adj[g.ID]
	seen := map[string]bool{}
	uniq := make([]string, 0, len(neighbors))
	for _, n := range neighbors {
		if !seen[n] {
			seen[n] = true
			uniq = append(uniq, n)
		}
	}
	sort.Slice(uniq, func(i, j int) bool {
		return degree[uniq[i]] > degree[uniq[j]]
	})

	b.WriteString("## Connections\n\n")
	maxN := min(30, len(uniq))
	for _, nid := range uniq[:maxN] {
		n, ok := nodeMap[nid]
		if !ok {
			continue
		}
		// Neighbors aren't necessarily emitted as their own wiki
		// articles — only communities and explicit god nodes are.
		// Render bare-label here so the article reads naturally
		// without producing dead links to non-existent files.
		fmt.Fprintf(&b, "- %s\n", n.Label)
	}
	if len(uniq) > maxN {
		fmt.Fprintf(&b, "- *... and %d more*\n", len(uniq)-maxN)
	}
	b.WriteString("\n")

	b.WriteString("---\n\n*Part of the gogfy knowledge wiki. See [index](index.md) to navigate.*\n")
	return b.String()
}

func indexArticle(communities map[string][]schema.Node, labels map[string]string, godNodes []schema.Node, communitySlugs map[string]string, godSlugs map[string]string, totalNodes, totalEdges int) string {
	var b strings.Builder
	b.WriteString("# Knowledge Graph Index\n\n")
	b.WriteString("> Auto-generated by gogfy. Start here — read community articles for context, then drill into god nodes for detail.\n\n")
	fmt.Fprintf(&b, "**%d nodes · %d edges · %d communities**\n\n", totalNodes, totalEdges, len(communities))
	b.WriteString("---\n\n")

	b.WriteString("## Communities\n")
	b.WriteString("(sorted by size, largest first)\n\n")

	// Sort by member count desc, then by label asc for ties.
	type entry struct {
		cid   string
		label string
		size  int
	}
	entries := make([]entry, 0, len(communities))
	for cid, members := range communities {
		entries = append(entries, entry{cid, labels[cid], len(members)})
	}
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].size != entries[j].size {
			return entries[i].size > entries[j].size
		}
		return entries[i].label < entries[j].label
	})
	for _, e := range entries {
		fmt.Fprintf(&b, "- [%s](%s.md) — %d nodes\n", e.label, communitySlugs[e.cid], e.size)
	}
	b.WriteString("\n")

	if len(godNodes) > 0 {
		b.WriteString("## God Nodes\n")
		b.WriteString("(most connected concepts — the load-bearing abstractions)\n\n")
		for _, g := range godNodes {
			fmt.Fprintf(&b, "- [%s](%s.md)\n", g.Label, godSlugs[g.ID])
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n\n")
	b.WriteString("*Generated by [gogfy](https://github.com/julianshen/gogfy)*\n")
	return b.String()
}

// safeFilenameRE matches characters that Windows reserves in filenames.
// We also collapse `/`, ` `, and `:` to dashes/underscores up-front for
// readability on every OS.
var safeFilenameRE = regexp.MustCompile(`[<>:"/\\|?*]`)

func safeFilename(name string) string {
	s := strings.ReplaceAll(name, "/", "-")
	s = strings.ReplaceAll(s, " ", "_")
	s = strings.ReplaceAll(s, ":", "-")
	s = safeFilenameRE.ReplaceAllString(s, "_")
	s = strings.Trim(s, ". ")
	// Truncate at rune boundary, not byte boundary — labels are
	// user-supplied and may contain multi-byte UTF-8 (non-ASCII names,
	// emoji-prefixed community labels, CJK source-file paths). Slicing
	// a string by byte index can produce invalid UTF-8 the filesystem
	// then rejects.
	if runes := []rune(s); len(runes) > 200 {
		s = string(runes[:200])
	}
	if s == "" {
		return "unnamed"
	}
	return s
}

// uniqueSlug returns base if it hasn't been used, otherwise base_2, _3, …
// Map keys are lowercase so that on case-insensitive filesystems
// (default on Windows, common on macOS) labels like "Auth" and "auth"
// collide correctly — they'd otherwise both try to write to "auth.md"
// (or one of those two cases) and clobber each other. The returned
// slug preserves the original case for readable filenames on
// case-sensitive filesystems.
//
// The unbounded loop terminates because `used` grows by at most one
// entry per call: at most len(used)+1 iterations are ever needed.
func uniqueSlug(used map[string]bool, base string) string {
	key := strings.ToLower(base)
	if !used[key] {
		used[key] = true
		return base
	}
	for i := 2; ; i++ {
		s := fmt.Sprintf("%s_%d", base, i)
		k := strings.ToLower(s)
		if !used[k] {
			used[k] = true
			return s
		}
	}
}

func sortedKeys(m map[string][]schema.Node) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// wikiMarkerFile is written into the output directory to mark it as
// gogfy-owned. clearStaleArticles refuses to delete *.md files from a
// directory that contains user markdown but no marker — so passing
// `gogfy wiki <graph> --out .` (or any arbitrary path) can't silently
// destroy a project's README.md or other markdown.
const wikiMarkerFile = ".gogfy_wiki"

// clearStaleArticles removes *.md files in dir IF the directory is
// gogfy-owned (contains wikiMarkerFile). Community labels can change
// between runs and stale orphan articles would otherwise accumulate.
// A directory with markdown but no marker is treated as user content
// and the function returns an error rather than touch it.
func clearStaleArticles(dir string) error {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return err
	}
	var (
		hasMarker bool
		mdFiles   []string
	)
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		if e.Name() == wikiMarkerFile {
			hasMarker = true
		}
		if strings.HasSuffix(e.Name(), ".md") {
			mdFiles = append(mdFiles, e.Name())
		}
	}
	if len(mdFiles) > 0 && !hasMarker {
		return fmt.Errorf("wiki: %s contains existing .md files but no %s marker — refusing to clear it (use a dedicated subdirectory)", dir, wikiMarkerFile)
	}
	for _, name := range mdFiles {
		if err := os.Remove(filepath.Join(dir, name)); err != nil {
			return err
		}
	}
	return nil
}

func writeArticle(path string, content string) error {
	return fsutil.WriteFileAtomic(path, []byte(content), 0644)
}
